# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-07-01 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20180727_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='standard_update_due_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 7, 1), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 7, 1), null=True),
        ),
    ]
